on:
    repository_dispatch:
        types: [inceident_report]
jobs:
    handle-incident:
        runs-on: ubuntu-latest
        steps:
            - name: print incident report
              run: echo "inceident report"