name: First workflow

on:
  push:
    branches:
     - master
jobs:
  example-jobs:
    runs-on: ubuntu-latest

    steps:
     - name: print welcome message
       run: echo "welcome to workflow agaain"

     - name: checkout repo
       uses: actions/checkout@v4.2.2
     - name: list repo files
       run: ls -la
