on:
    push:
        branches:
            - master
            - develop
        paths:
            - 'src/**'
    pull_request:
        branches:
            - master
            - develop
        paths:
            - 'src/**'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2

            - name: Run tests
              run: python ./src/main.py